name       : python-h5py
version    : 3.7.0
release    : 8
source     :
    - https://github.com/h5py/h5py/releases/download/3.7.0/h5py-3.7.0.tar.gz : 22cdc29324f39102c89542845b02241f8c5a7b180bbed8cc0b14ff72a1c0e478
license    : BSD-3-Clause
component  : programming.python
summary    : A Pythonic interface to the HDF5 binary data format
description: |
    The h5py package provides both a high- and low-level interface to the HDF5 library from Python. The low-level interface is intended to be a complete wrapping of the HDF5 API, while the high-level component supports access to HDF5 files, datasets and groups using established Python and NumPy concepts. A strong emphasis on automatic conversion between Python (Numpy) datatypes and data structures and their HDF5 equivalents vastly simplifies the process of reading and writing data from Python.
builddeps  :
    - pkgconfig(hdf5)
    - cython
    - numpy
    - python-pkgconfig
    - python-six
rundeps    :
    - numpy
    - python-six
build      : |
    # Allow newer numpy
    sed -i 's/numpy ==/numpy >=/g' setup.py
    %python3_setup
install    : |
    %python3_install
