name       : python-h5py
version    : 3.6.0
release    : 6
source     :
    - https://github.com/h5py/h5py/releases/download/3.6.0/h5py-3.6.0.tar.gz : cd4f31b19a3f16a958856655e644f28ab2e208f9e13cbddd3831161beb0baf4b
license    : BSD-3-Clause
component  : programming.python
summary    : A Pythonic interface to the HDF5 binary data format
description: |
    The h5py package provides both a high- and low-level interface to the HDF5 library from Python. The low-level interface is intended to be a complete wrapping of the HDF5 API, while the high-level component supports access to HDF5 files, datasets and groups using established Python and NumPy concepts. A strong emphasis on automatic conversion between Python (Numpy) datatypes and data structures and their HDF5 equivalents vastly simplifies the process of reading and writing data from Python.
builddeps  :
    - pkgconfig(hdf5-1.10.4)
    - cython
    - numpy
    - python-pkgconfig
    - python-six
rundeps    :
    - numpy
    - python-six
build      : |
    # Allow newer numpy
    sed -i 's/numpy ==/numpy >=/g' setup.py
    %python3_setup
install    : |
    %python3_install
